name: sdlm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.0=py3.9_cuda11.3_cudnn8.3.2_0
  - pip
  - pip:
      - sacremoses
      - rouge_score
      - accelerate==0.12.0
      - ipython==8.4.0
      - tensorboard==2.9.1
      - datasets
      - transformers==4.25.1
      - diffusers==v0.7.2
      - nltk
      - sentencepiece
      - sacrebleu
      - evaluate
      - bert_score
